
export const FETCH_NEW_MOVIES = 'FETCH_NEW_MOVIES';
export const FETCH_MOVIE_DETAIL = 'FETCH_MOVIE_DETAIL';
export const FETCH_MOVIE_LIST = 'FETCH_MOVIE_LIST';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_MOVIES_BY_CATEGORY = 'FETCH_MOVIES_BY_CATEGORY';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_MOVIES_BY_COUNTRY = 'FETCH_MOVIES_BY_COUNTRY';
export const FETCH_MOVIES_BY_YEAR = 'FETCH_MOVIES_BY_YEAR';
